$pdf_mode = 1; # Use pdflatex
$bibtex_use = 'biber'; # Use biber, not bibtex
system("tlmgr install fontspec geometry hyperref xcolor titlesec fontawesome5 xifthen pgf paracol ragged2e enumitem tcolorbox academicons");
